version: '3'
services:
  game:
    build:
      context: backend
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - JWT_SECRET=801ae83cce1537c16081fc4991763a6f0d33a6ed6c953d99a7fff77c1a00fafd
      - JWT_EXP_TIME=144000
      - SPRING_DATASOURCE_URL=jdbc:mysql://gamedb:3306/geoguessr
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - gamedb
  gamedb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: geoguessr
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - game-db:/var/lib/mysql

volumes:
  game-db:
