version: '3'
services:
#  game:
#    build:
#      context: backend
#    ports:
#      - "8080:8080"
  gamedb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: geoguessr
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - game-db:/var/lib/mysql

volumes:
  game-db: